<?php

// The below function is for rendering user registration form suggestion
function suboot_theme_suggestions_form_alter(array &$suggestions, array $variables) {
$suggestions[] = 'form__' . str_replace('-','_', $variables['element']['#id']);
}
function suboot_theme($existing, $type, $theme, $path) {

  return [
    'form__user-login-form' => [
      '#theme' => 'form--user-login-form',
      'render element' => 'form',
    ],
  ];

}

// --END OF USER FORM SUGGESTION
